notifications:
  email: false
  slack:
    secure: ofhJwfihQoAS8tvVVZorEN00kod+aQVEO58cDgVKOuc8x47G0AZn+QNjDDamrif/Y3zm3J24tyEJAJ2g5gf5F3w41OQbCHm9rWt3PrUMfc5ykCRuzOPT70Uu2AdTQO3AjNNXYNuO5o962aW9zKo1uqjse+zGl8CGlE8uU3GeS/qHU2/eZD9b13YGlI2SONahna6tgomavSC0qgyJRFRAAqsZ6EGD/Kk4dN/ZSL+pmpqdleiNYRerIBFEYXARcXI0KAvPtAaioNe8SLwC+NmNuj8MqJmH28ZbMbz3+qJG1bpiK+jpVLLSuFWGfbYhavtT8GuVEkAzbyj0hQJFvlWQwwcgHf6W1jzIGaKOHH3sGcC3OqsE9a1KTVUeRZ21XAp14dEtBufMlUdlNpbLF80Y691GdXVyobZSwFV+pWjIVPAehxJb8TX0IEEciyGxL1B0EEWWgmcFsqKTmmVCI1qYYRrXI4AuMfPTZ9CRF8WSLkPjVRkjyWeck4FfHSK8CbtoNAl+hN6dnPDqhxcVsU1Wh9+lXBYGdk2iQwCzJVelMuPBOxFLM2lVUlLM65DoEjWDeZMzao2bTL9biFsOwHQf26Las9l6SsuIGhElHjloJxv+oyzl4oGwsY+XjdRUuM2Dn4aDpfiNIHmXUNe45uTQoHSCEaent+nZytKMiTy6zF0=
before_install:
- nvm install stable
- nvm use stable
install:
- npm install
- npm rebuild node-sass
before_script: echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
- npm run build
